### ISSUE TITLE
Wrong tab index 

### ISSUE THREAD

**Issue by ghost** [guilhermearaujo/GUITabPagerViewController#10]
Sometimes if you swipe quickly between the tabs the tab index shows to the wrong tab

**Comment by guilhermearaujo** [comment]
I couldn't reproduce it. Can you give more details?
How many tabs are you using? Do you swipe back and forth, or in a single direction?

**Comment by ghost** [comment]
We are testing on an iPhone 5C with an application that uses 5 tabs. We swipe back and forth and in some case the index in showing the second tab (from the left) but i cannot swipe further to the right because the viewpager is already to the leftmost viewcotroller. 

In the image below you can see that you cannot swipe more to the left but the index is not in the leftmost position

![img_0006](https://cloud.githubusercontent.com/assets/11830121/7024681/3a8fd2da-dd47-11e4-9b51-c13176c8b881.PNG)

Thanks

**Comment by guilhermearaujo** [comment]
I kept trying but couldn't reproduce it. How easy or how hard is it for you to achieve that state?
The view controller that is being shown, is it the left-most controller? I mean, does it reflect correctly the content of the "Main" tab (despite the indicator display "Local")?
If you swipe from the right, will the indicator remain in the "Local" tab?

**Comment by ghost** [comment]
Ok, its not something that happens every time and I only managed to produce on iPhone 5C and you must swipe between tabs quickly, I tried on iPad too and I was unable to reproduce it. I assume that it has to do with the horizontal scroll on the tabs and because on iPad I did not have scroll because screen was bigger the issue was not appearing.

The view controller was the left most and the data were the correct ones, only the tab indicator was wrong. When you swipe right the indicator will remain to Local, in other words once you swipe again it comes back to the correct order.

I will have a look in your source code too and investigate more, I assume that the issue has to do with the scroll.

Thanks

**Comment by filipandrei87** [comment]
Hi. What is the status on this?

I found that on older devices using iOS 7, page view controller delegate methods are not reliable for setting the index when fast swiping through pages. Maybe this is the same as I saw you also use a pageviewcontroller

**Comment by jayjayesh** [comment]
i am facing same problem of tab indexing. is anyone solve this issue?

Thnks
