### ISSUE TITLE
header view mixed with the status bar when the viewController is not in a container

### ISSUE THREAD

**Issue by scplwq** [guilhermearaujo/GUITabPagerViewController#12]
Perhaps it was caused by this sentence in GUITabScrollView.m :
[contentView setTranslatesAutoresizingMaskIntoConstraints:NO].
it fixed after i delete it.

And the header view doesn't show well when rotation changed.

sorry for my poor english

**Comment by mariospoly** [comment]
After deleting this line it worked. Thanks.
