### ISSUE TITLE
Not working on ios9

### ISSUE THREAD

**Issue by dineshbhadane** [guilhermearaujo/GUITabPagerViewController#21]
[NSLayoutConstraint constraintWithItem:attribute:relatedBy:toItem:attribute:multiplier:constant:]: A constraint cannot be made between a leading/trailing attribute and a right/left attribute. Use leading/trailing for both or neither.

**Comment by kcandr** [comment]
Duplicate https://github.com/guilhermearaujo/GUITabPagerViewController/issues/19 - @dineshbhadane open GUITabScrollView.m at line 113 and change `NSLayoutAttributeLeft` to `NSLayoutAttributeLeading`.

**Comment by dineshbhadane** [comment]
Thanks,It's working fine....
