### ISSUE TITLE
the indicator is wrong displaced when appear

### ISSUE THREAD

**Issue by maimake** [guilhermearaujo/GUITabPagerViewController#22]
```
- (NSInteger)numberOfViewControllers {
  return 3;
}
```

![qq20151011-0 2x](https://cloud.githubusercontent.com/assets/492028/10415034/e9e43bce-701b-11e5-926d-effd3fe7d07c.png)

**Comment by mariospoly** [comment]
I had the same issue. I solved it by adding the following line: 
[self animateToTabAtIndex:index animated:NO];
to the end of the following function in GUITabScrollView.m file
- (void)_initTabbatAtIndex:(NSInteger)index

**Comment by josluimg** [comment]
Me too. Thanks for the fix @mariospoly . It solved the problem

**Comment by smitshah27** [comment]
try writing this line of code in GUITabScrollView.m file after line no 133 (i.e adding constraints)
[self layoutIfNeeded];

**Comment by guilhermearaujo** [comment]
Fixed with #32. A new Pod release will be out soon.
