### ISSUE TITLE
How to disable tab bar indicator?

### ISSUE THREAD

**Issue by akgulem** [guilhermearaujo/GUITabPagerViewController#23]
Hello,

I am using this cocoa pod and able to use it properly. However, I want to disable tab bar indicator. I know how to disable tab bar indicator if I inherit directly from Scroll View since it has necessary methods, but I inherit from GUITabPagerViewController in my view controller and there isn't any method associated with that. Thus, I came up with an idea of inheriting from GUITabPagerViewController and GUITabScrollView both, however Objective C does not allow multiple inheritance.

Is there an idea how I can achieve this?

**Comment by guilhermearaujo** [comment]
You could make the `tabColor` delegate return any color with alpha = 0. Then it will be transparent.
