### ISSUE TITLE
How to move to a specific tab index  on button click ? 

### ISSUE THREAD

**Issue by nnaavveenn35** [guilhermearaujo/GUITabPagerViewController#24]
Hi,
I have a collectoin view and when i click on one item i need to open another view controller with  GUITabPagerViewController  and show corresponding tab. At this moment always it opens first tab.

Is there any solution for this?

**Comment by BasimMajeed** [comment]
These function are already defined:
- (void)selectTabbarIndex:(NSInteger)index;
- (void)selectTabbarIndex:(NSInteger)index animation:(BOOL)animation;

[self selectTabbarIndex:20];
[self selectTabbarIndex:20 animation:YES];
