### ISSUE TITLE
How to give the equal spacing between three tabs 

### ISSUE THREAD

**Issue by SusheelYadav455** [guilhermearaujo/GUITabPagerViewController#34]
Hi , 
Firstly i would like to thank you  for providing this SDK . It is very userfriendly . But i would like to know how to give the equal spacing between three tabs. I have a scenario where i have three tabs (like Tab 1 , Tab2 , Tab 3). Actually in your SDK tabs are starting from Middle . Could you say me the appropriate method to give equal spacing . It would be helpful in my project . 

Thank you , 
Waiting for your reply

**Comment by guilhermearaujo** [comment]
There is no way to add a gap between tabs unless you tweak the code to work like that.
What you could instead is to use a custom `UIView` whose width is fixed at 1/3 of the device's width.
