### ISSUE TITLE
Controllers inside the page controller won't resize themselves when resizing or rotating

### ISSUE THREAD

**Issue by internalG** [guilhermearaujo/GUITabPagerViewController#35]
It can be reproduced when you rotate on ipad. iOS 8 has worse situation than iOS 9 and 10.

**Comment by guilhermearaujo** [comment]
What version are you using?

**Comment by internalG** [comment]
The latest version. The tab bar line also won't redraw when you rotate from portrait to landscape.

**Comment by internalG** [comment]
I'm trying to fix it, but can't find it yet. It seems the constraints have no effects. You can run your sample app on the ios 8 simulator, and rotate from portrait to landscape to reproduce it.

**Comment by guilhermearaujo** [comment]
@internalG I'm running the sample app on iOS 10 emulator and it seems fine to me. I'll download the iOS 8 simulator and try it. Meanwhile, do you have a sample project of your own that I could see this issue happening?

**Comment by internalG** [comment]
https://github.com/internalG/GUITabPagerViewController/blob/rotation/rotation1.png
https://github.com/internalG/GUITabPagerViewController/blob/rotation/rotation2.png

You can see the tabs position and separator length are not right after rotation.

**Comment by guilhermearaujo** [comment]
Fixed on v0.1.3
