### ISSUE TITLE
Only Last View is Showing for Title View

### ISSUE THREAD

**Issue by Dhiru-Dev** [guilhermearaujo/GUITabPagerViewController#38]
i have used  `ViewForTitle` datasource method .
but i only last View is Visible ,,,i this all views are being added on one on another  so the are hiding 
i tried incrememting X position according to the Index number but not able to do that 
![screen shot 2017-05-24 at 1 00 15 pm](https://cloud.githubusercontent.com/assets/16178823/26391783/bd035206-4081-11e7-93d1-d7b3e37cbb85.png)

when i implement `TitleForIndex` is works fine  .please help ,me out
![screen shot 2017-05-24 at 1 01 20 pm](https://cloud.githubusercontent.com/assets/16178823/26391856/0692e30a-4082-11e7-9bd2-3cd622f3dfa3.png)

**Comment by Dhiru-Dev** [comment]
i was using 0.0.8 i updated to latest 0.1.3   issue fixed , but now i have also another problem .
i have a toggle button in Right side which is Hiding the Last Item , how can i set this ScrolleView ContentSize , in which method you are changing the ContentSize i was unable to find the Method in you class ,

![screen shot 2017-05-24 at 3 25 36 pm](https://cloud.githubusercontent.com/assets/16178823/26397979/ade3078a-4095-11e7-81bc-cc95e47dada9.png)
 
if i will change the ContentSizeWidth+50  , that will solve my problem ???

**Comment by guilhermearaujo** [comment]
The tabs scrollview, as is, will not be able to do what you want. You will need to customize it.
