### ISSUE TITLE
Tab position

### ISSUE THREAD

**Issue by Urkman** [guilhermearaujo/GUITabPagerViewController#4]
Add possibility to show tabs at bottom of the screen

**Comment by Urkman** [comment]
It would also be great, to position the tab free inside the controllers view...
e.g. not direct below the navigation bar, but x pixels below it...

**Comment by Urkman** [comment]
I've done parts of this in my fork. Take a look here, if you are interested:
https://github.com/Urkman/GUITabPagerViewController

There it is possible to add the paging view to a storyboard view...

**Comment by Jallynme** [comment]
It would also be great, if we can chage background and text title attribute or set show bottom line : P
