### ISSUE TITLE
IOS 7 Tab Title text missing!

### ISSUE THREAD

**Issue by etamity** [guilhermearaujo/GUITabPagerViewController#5]
![ios simulator screen shot 6 mar 2015 12 07 33](https://cloud.githubusercontent.com/assets/3015181/6525118/68ac89ea-c3f9-11e4-884a-0c2d3f803de5.png)

Hi , please check this, i run the demo on ios7 , is this a bug?

**Comment by guilhermearaujo** [comment]
Bug confirmed, I'm working on this.

**Comment by guilhermearaujo** [comment]
Fixed on new release 0.0.2.
