### ISSUE TITLE
Make currentIndex property public ?

### ISSUE THREAD

**Issue by Flox06** [guilhermearaujo/GUITabPagerViewController#6]
Hi !

What about setting the **currentIndex** property to public in order to know which tab controller is actually displayed ? :)

BTW, thx for your work !

Best,

**Comment by guilhermearaujo** [comment]
Nice idea. I will work on that soon.

**Comment by Flox06** [comment]
:beers:  !

**Comment by guilhermearaujo** [comment]
Included in release 0.0.4.
