### ISSUE TITLE
Change tab color 

### ISSUE THREAD

**Issue by ghost** [guilhermearaujo/GUITabPagerViewController#9]
Please provide access to the tab color not only to the line under the tab.

**Comment by guilhermearaujo** [comment]
Just to make sure, you're talking about the tab bar background color, right?

**Comment by ghost** [comment]
Yes, exactly

**Comment by guilhermearaujo** [comment]
I've added data source methods for both the tab background and title font face.
Pod specs will be updated later today.

**Comment by guilhermearaujo** [comment]
FYI, Pod version 0.0.5 is available now
